version: '3.9'

services:

  weludic-api:
    build:
      context: .
      dockerfile: src/WeLudic.PublicApi/Dockerfile
    ports:
      - '5000:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - "mysql"

  mysql:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=weludicdb
      - MYSQL_ROOT_PASSWORD=RooT146@1
    ports:
      - '3306:3306'

  seq:
    image: datalust/seq:latest
    volumes:
      - /path/to/seq/data:/data
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

volumes:
  mysql-data: